### ISSUE TITLE
Support for Atari 400/800?

### ISSUE THREAD

**Issue by mikesk8** [ascrnet/HW-Detect#1]
Hi, Does your program support Atari 400800 as well? Thanks, Michael

**Comment by ascrnet** [comment]
Sorry, it only works on XL/XL and XEGS lines

**Comment by mikesk8** [comment]
Thank you for the fast answer. Would you be considering to add 800 piece? Then, does the Antic/GTIA detection works in 400/800 in your program? I am asking as my hardware is a mix and I would like to detect what is really inside.

**Comment by ascrnet** [comment]
i answered you in atariage
